### ISSUE TITLE
Kraken web hook message

### ISSUE THREAD

**Issue by shimuldn** [thibaultyou/tradingview-alerts-processor#18]
Hi,
I am doing order on kraken spot.

`{ "stub": "kraken", "direction": "long", "symbol": "ADA/USD", "size": "100" }`

Getting error message:
`- Failed to open position on ADA/USD. -> {"name":"InvalidOrder"}`
`"direction": "buy"` also error.

Doing ADAUSD
`- Failed to open position on ADAUSD.`

What I am doing wrong?

**Comment by oldrich-safar** [comment]
Same with Binance.

**Comment by shimuldn** [comment]
> Same with Binance.

Binance is working fine.
Use this formate for Binance future.
`{ "stub": "stub", "direction": "long", "symbol": "ETH/USDT", "size": "100" }`

**Comment by oldrich-safar** [comment]
Sorry my fault, yes its working. I used:
` "symbol": "ETHUSDT"`

**Comment by shimuldn** [comment]
> Sorry my fault, yes its working. I used:
> ` "symbol": "ETHUSDT"`

Formatting need to be as per exchange. Not your fault documentation is the thing here.

**Comment by thibaultyou** [comment]
Hello there, yeah I'm sorry I need to update the documentation to be more explicit, you need to use per exchange format for symbols. As this tool has initially been written for FTX the documentation is using FTX symbols for now.

You can check exchange symbols with the /markets route.

**Comment by shimuldn** [comment]
If anyone in future looking for this issue just use 
`{ "stub": "kraken", "direction": "long", "symbol": "ADA/USD", "size": "20" }` and make sure you are using `size` more than minimum for the exchange for that coin.
