### ISSUE TITLE
FTX position not closed

### ISSUE THREAD

**Issue by shimuldn** [thibaultyou/tradingview-alerts-processor#27]
Log says position closed but in exchange order was cancelled.
Verifying the order status `filledSize` is required.

<img width="1117" alt="Screen Shot 2021-09-13 at 9 25 05 pm" src="https://user-images.githubusercontent.com/12117121/133118910-5aabdeb1-0e14-4df9-96c5-22a0e639635c.png">
<img width="276" alt="Screen Shot 2021-09-13 at 9 37 12 pm" src="https://user-images.githubusercontent.com/12117121/133118922-a60313ee-26d7-4ae3-8423-b9dd94941629.png">

```
- $$$ Closing 6 SECO-PERP of open position / available balance (~ 141.07 $US).
Trade c61a4df0-xxxxxxxxxx-yyyyyyyyyyyyyyy executed in 1259 ms.
```

**Comment by mrsegen** [comment]
I can't comment on the specific issue you're finding. 

But, generally, I can say that, the way things are built at the moment, the "Trade [...] executed ..." message actually just means that TAP received and has begun processing the trade request. The actual processing of the trade happens asynchronously - with the result appearing in the TAP logs.

On that (tangential) point, perhaps we could make a 200 success response dependent on successful completion of trade. That would improve messaging and reduce some need to get on the server itself. @thibaultyou, are there any downsides (aside from potential refactor needs) to making this change?

**Comment by mrsegen** [comment]
@thibaultyou That makes sense. Would it make sense to maybe replace "trade has been executed" with "traded has been queued"?
