### ISSUE TITLE
Can it only be used in AWS? I have other servers. If I deploy them

### ISSUE THREAD

**Issue by goushijie** [thibaultyou/tradingview-alerts-processor#43]
Can it only be used in AWS? I have other servers. If I deploy them, thank you very much

**Comment by leifjones** [comment]
It can be deployed anywhere you can run NodeJS or anywhere you can run a Docker container

I just also needs to be accessible for TradingView to send it requests, and it needs to have access to your exchange(s)

**Comment by goushijie** [comment]
It would be perfect if there were more detailed documentation，Thank you very much

**Comment by goushijie** [comment]
I am looking forward to deploying at ubuntu，How should I deploy？

**Comment by goushijie** [comment]
my SystemOS ubuntu 20 and Node.js is v10.19.0,The installation steps are as follows

Clone the app sources :

git clone https://github.com/thibaultyou/tradingview-alerts-processor.git
Install app and configure the server :

cd tradingview-alerts-processor/
sh install.node.sh
You should see npm entry with online status, if this is not the case reconfigure PM2 and check again with :

pm2 start npm -- start
pm2 save
pm2 status npm

pm2 logs npm Error are as follows
<img width="880" alt="image" src="https://user-images.githubusercontent.com/7100718/174732932-4e5adf91-0235-45b7-a408-f2ffc32901e9.png">

**Comment by goushijie** [comment]
I have used docker to install is OK
It is even better if there is a UI. View the logs received by the call through the UI
